area/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from area import views
from area.views import (AreaCreateView,
						 AreaDeleteView,
						 AreaListView,
						 AreaUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(AreaCreateView.as_view()), name='newArea'),
	url(r'^lista/areas', login_required(AreaListView.as_view()), name='listAreas'),
	url(r'^modificar/area/(?P<pk>\d+)', login_required(AreaUpdateView.as_view()), name='updateArea'),
	url(r'^eliminar/area/(?P<pk>\d+)', login_required(AreaDeleteView.as_view()), name='deleteArea'),
	url(r'^menu-areas/', login_required(views.menuAreas), name='menu_areas')
]

insumos/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from insumos import views

from insumos.views import InsumosCreateView, InsumosDeleteView, InsumosListView, InsumosUpdateView

urlpatterns = [
	url(r'^nuevo/insumos/', login_required(InsumosCreateView.as_view()), name='newInsumo'),
	url(r'^lista/insumos/$', login_required(InsumosListView.as_view()), name='listInsumo'),
	url(r'^editar/insumos/(?P<pk>\d+)', login_required(InsumosUpdateView.as_view()), name='updateInsumo'),
	url(r'^eliminar/insumos/(?P<pk>\d+)', login_required(InsumosDeleteView.as_view()), name='deleteInsumo'),

    ##### url del ajax ####
    url(r'^insumo/detalle/$', views.DetailAjax, name='home')    

]

prendas/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from prendas.views import (PrendasCreateView, 
							PrendasDeleteView, 
							PrendasListView, 
							PrendasUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(PrendasCreateView.as_view()), name='newPrenda'),
	url(r'^lista/', login_required(PrendasListView.as_view()), name='listPrenda'),
	url(r'^modificar/(?P<pk>\d+)', login_required(PrendasUpdateView.as_view()), name='updatePrenda'),
	url(r'^eliminar/(?P<pk>\d+)', login_required(PrendasDeleteView.as_view()), name='deletePrenda'),
]

scir/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from usuario import views

urlpatterns = [
	url(r'^$', views.index, name='first'),
	url(r'^menu/$', login_required(views.menuPrincipal), name='menuPrincipal'),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^area/', include('area.urls', namespace='area')),
    url(r'^prendas/', include('prendas.urls', namespace = 'prendas')),
    url(r'^insumos/', include('insumos.urls', namespace = 'insumos')),
    url(r'^solicitud/', include('solicitud.urls', namespace='solicitud')),
    url(r'^mantenimiento/', include('manto.urls', namespace='manto')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

solicitud/urls.py
from django.conf.urls import url
from solicitud import views
from solicitud.views import RegistroCreateView, ReporteSolicitud, Reporte
from django.contrib.auth.decorators import login_required

urlpatterns =[
	
    url(r"^servicio/", login_required(RegistroCreateView.as_view()), name="newSolicitud"),
	url(r'^reporte/',login_required(Reporte.as_view()) , name='reporte'),
	url(r'^menu-report/', login_required(views.menu_report), name='menu_report'),
	url(r'^solicitud-pdf/$', login_required(ReporteSolicitud.as_view()) , name='solicitud_pdf')
	
]

usuario/urls.py
from django.conf.urls import url

from usuario import views
from usuario.views import UserListView

urlpatterns = [
	url(r'^registrar/', views.signUp, name='signup'),
	url(r'^lista/', UserListView.as_view(), name='listUser'),
]

templates/menus/menuAreas.html
{% extends "base.html" %}
{% block content %}
	<h2 class="text-center">Areas</h2>
 <section class="menus">
   <div class="colum-1">

   {% for area1 in colum1  %}
   		<button><a href="{% url 'solicitud:newSolicitud'}">{{ area1.nombre_area }}</a></button>
   {% endfor %}
      <!--button><a href="servicio.html">Clin-1</a></button>
      <button>Clin-2</button>
      <button>Clin-3</button>
      <button>Clin-4</button>
      <button>Clin-5</button>
      <button>Clin-6</button>
      <button>Clin-7A</button>
      <button>Clin-7B</button>
      <button>Clin-Recup</button>
      <button>Clin-UTIR</button>
      <button>Clin-UCIR</button-->
   </div>

   <div class="colum-2">
      {% for area2 in colum2 %}
        <button><a href="{% url 'solicitud:newSolicitud' area2%}">{{ area2.nombre_area }}</a></button>
      {% endfor %}
      <!--button>CEYE</button>
      <button>CIRU</button>
      <button>Urg</button>
      <button>Bronco</button>
      <button>B-san</button>
      <button>Hemo</button>
      <button><a href="serv-edif1.html">Edif-1</a></button>
      <button><a href="serv-edif2.html">Edif-2</a></button>
      <button>Quimio</button>
      <button>Inhalo</button>
      <button type="button" name="button">Otro Serv</button-->
   </div>


   <div class="colum-3">
      <!--button >Biote</button>
      <button>CirExp</button>
      <button>ClinSue</button>
      <button>Epoc</button>
      <button>Pato</button>
      <button>InvAutoin</button>
      <button>Infecto</button>
      <button>Asma</button>
      <button>C.I.E.N.I</button>
      <button>Otro Inves</button>
      <button type="button" name="button">Quirofano Urg.</button-->
   </div>

   <div class="colum-4">
     <!--button>Medicos</button>
     <button>Intendencia</button>
     <button>RopaNva</button>
     <button>Dir. Admon.</button>
     <button>Dir. Gral.</button>
     <button>Audio Visual</button>
     <button>Morfologia</button>
     <button>Rehab. Respiratoria</button>
     <button>Otra</button>
     <button>Otra-1</button>
   </div-->
 </section>

{% endblock content %}

templates/menus/menuPrincipal.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<section class=" container contenedor">
	<h1 class=" text-center">Menú</h1>
	{% if request.user.is_superuser %}

	<div class="row mt-3 text-center">
		<div class="col-4">
			<a href="{% url 'usuario:listUser' %}">
				<img class="" src="{% static 'img/menuPrincipal/cliente.png' %}" alt="">
			</a>
			<p>Usuarios</p>
		</div>

		<div class="col-4">
			<a href="{% url 'insumos:listInsumo' %}">
				<img src="{% static 'img/menuPrincipal/insumo.png' %}" alt="" width="150" height="150">
			</a>
			<p>Insumos</p>
		</div>
		<div class="col-4">
			<a href="{% url 'prendas:listPrenda' %}">

				<img src="{% static 'img/menuPrincipal/prenda.png' %}" alt="" width="150" , height="150">

			</a>
			<p>Prendas</p>
		</div>
	</div>

	<div class="row mt-3 text-center">
		<div class="col-4">
			<a href="{% url 'area:listAreas' %}">

				<img src="{% static 'img/menuPrincipal/area.png' %}" alt="" width="150" height="150">

			</a>
			<p>Áreas</p>
		</div>
		<div class="col-4">
			<a href="{% url 'solicitud:newSolicitud' %}">

				<img src="{% static 'img/menuPrincipal/solicitud.png' %}" alt="" width="150" height="150">

			</a>
			<p>Solicitud</p>
		</div>
		<div class="col-4">
			<a href="{% url 'solicitud:menu_report' %}">

				<img src="{% static 'img/menuPrincipal/reportes.png' %}" alt="" width="150" height="150">

			</a>
			<p>Reportes</p>
		</div>
	</div>

	{% else %}
	<div class="row">
		<a href="{% url 'solicitud:newSolicitud' %}">
			<img src="{% static 'img/menuPrincipal/solicitud.png' %}" alt="">
		</a>
	</div>
	{% endif %}
</section>
{% endblock content %}

{% block modal-ventana %}
<div class="modal fade" id="manto" role="dialog">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content" id="datos">
			

		</div>
	</div>
</div>
{% endblock modal-ventana %}

templates/menus/menuReporte.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class=" container mt-5" name="reportes">
  <h3>Reportes</h3>
  <form action="{% url 'solicitud:reporte' %}" method="get">
  {% csrf_token %}
    <div class="form-group">
      <label for=""></label>
      <select class="custom-select" name="anual" id="anio">
          <option value="0" selected>-selecciona un año-</option>
          <option value="2019">2019</option>
          <option value="2018">2018</option>
          <option value="2017">2017</option>
          <option value="2016">2016</option>
          <option value="2015">2015</option>
          <option value="2014">2014</option>
      </select>

      <select class="custom-select" name="options" id="options" disabled="disabled">
        <option value="0" selected>-Selecciona una-</option>
        <option value="1">semestral</option>
        <option value="2">trimestral</option>
        <option value="3">bimestral</option>
        <option value="4">mensual</option>
      </select>
      <select class="custom-select" name="option" id="option" disabled="disabled">
        <option value="0" selected>Selecciona una</option>
      </select>
    </div>
    <button type="submit" class="btn btn-success">Generar reporte</button>
  </form>
</div>


{% endblock content %}