area/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from area import views
from area.views import (AreaCreateView,
						 AreaDeleteView,
						 AreaListView,
						 AreaUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(AreaCreateView.as_view()), name='newArea'),
	url(r'^lista/areas', login_required(AreaListView.as_view()), name='listAreas'),
	url(r'^modificar/area/(?P<pk>\d+)', login_required(AreaUpdateView.as_view()), name='updateArea'),
	url(r'^eliminar/area/(?P<pk>\d+)', login_required(AreaDeleteView.as_view()), name='deleteArea'),
	url(r'^menu-areas/', login_required(views.menuAreas), name='menu_areas')
]

manto/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from manto.views import MantenimientoCreateView, MantenimientoListView, MantenimientoUpdateView, MantenimientoDeleteView
from manto import views

urlpatterns = [
    url(r'^nuevo/', login_required(MantenimientoCreateView.as_view()), name='newManto'),
    url(r"^modificar/(?P<pk>\d+)", login_required(MantenimientoUpdateView.as_view()), name="updateManto"),
    url(r"^eliminar/(?P<pk>\d+)", login_required(MantenimientoDeleteView.as_view()), name="deleteManto"),
    
    url(r'^lista/$', login_required(MantenimientoListView.as_view()), name='listManto'),
    url(r"^lista/(?P<pk>\d+)", login_required(views.MantenimientoRealizadoUpdate), name="checkList"),
    url(r'^fecha_manto/$', login_required(views.fechaManto), name="fechaManto"),
    
]

scir/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from usuario import views

urlpatterns = [
	url(r'^$', views.index, name='first'),
	url(r'^menu/$', login_required(views.menuPrincipal), name='menuPrincipal'),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^area/', include('area.urls', namespace='area')),
    url(r'^prendas/', include('prendas.urls', namespace = 'prendas')),
    url(r'^insumos/', include('insumos.urls', namespace = 'insumos')),
    url(r'^solicitud/', include('solicitud.urls', namespace='solicitud')),
    url(r'^mantenimiento/', include('manto.urls', namespace='manto')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

manto/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Mantenimiento(models.Model):


    class Meta:
        verbose_name = "Mantenimiento"
        verbose_name_plural = "Mantenimientos"

    fecha = models.DateField(auto_now=False)
    descripcion = models.CharField(max_length=300)
    aplicado = models.BooleanField(default=False)

    def __str__(self):
        return self.descripcion

manto/forms.py
from django import forms
from manto.models import Mantenimiento

class MantenimientoForm(forms.ModelForm):
    
    class Meta:
        model = Mantenimiento
        fields = ("fecha", "descripcion")

        widgets = {
            'descripcion' : forms.Textarea(attrs={
                'class':'form-control',
                'cols':40,
                'rows':6,
            }),

            'fecha': forms.DateInput(attrs={
                'class': 'form-control datepicker'
            })
        }

        labels = {
            'fecha':'Fecha del servicio',
            'descripcion':'Descripcion del Servicio'
        }

manto/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.core import serializers

from django.views.generic.edit import (
		CreateView,
		UpdateView,
		DeleteView,
	)
from django.views.generic import ListView

from manto.models import Mantenimiento
from manto.forms import MantenimientoForm

# Create your views here

class MantenimientoCreateView(CreateView):
    model = Mantenimiento
    template_name = "manto/mantoNew.html"
    form_class = MantenimientoForm
    success_url = reverse_lazy("manto:listManto")

    def get_context_data(self, **kwargs):
        context = super(MantenimientoCreateView, self).get_context_data(**kwargs)
        if 'formManto' not in context:
            context["formManto"] = self.form_class(self.request.GET) 
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        formManto = self.form_class(request.POST)
        if formManto.is_valid():
            manto = formManto.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=formManto))

class MantenimientoListView(ListView):
    model = Mantenimiento
    template_name = "manto/mantoList.html"

class MantenimientoUpdateView(UpdateView):
    model = Mantenimiento
    template_name = "manto/mantoNew.html"
    form_class = MantenimientoForm
    success_url = reverse_lazy('manto:listManto')

class MantenimientoDeleteView(DeleteView):
    model = Mantenimiento
    template_name = "manto/mantoDelete.html"
    success_url = reverse_lazy('manto:listManto')



def MantenimientoRealizadoUpdate(request, pk):
    #mantenimiento = Mantenimiento.objects.get(id=id_manto)
    manto = get_object_or_404(Mantenimiento, pk=pk)
    manto.aplicado=True
    manto.save(update_fields=["aplicado"])
    return HttpResponseRedirect(reverse_lazy("manto:listManto"))

def fechaManto(request):
    if request.is_ajax:
        fecha = request.GET.get('fecha')
        manto = Mantenimiento.objects.filter(fecha=fecha)
        data = serializers.serialize('json', manto, fields={'fecha','aplicado', 'descripcion'})
    else:
        data='fail'
    return HttpResponse(data, content_type='application/json')

templates/manto/mantoDelete.html
{% extends 'base.html' %}
{% block content %}
<div class="container contenedor">
	<div class="row">
		<h1 class="text-align-center">¿Estás seguro que deseas borrar el mantenimiento?</h1>
		<div class="col-sm-6 col-sm-offset-3">
			<form method="POST">{% csrf_token %}
		    	<input class="btn btn-danger btn-lg" type="submit" value="Eliminar" />
		    	<br/>
			</form>
			
			<a href="{% url "manto:listManto" %}"><button class="btn btn-primary btn-lg">Cancelar</button></a>
		</div>
	</div>
</div>
{% endblock %}

templates/manto/mantoList.html
{% extends 'base.html' %}

{% block content %}
<div class="container contenedor">
    {% if object_list %}
    <h1 class="text-center">Lista de mantenimientos</h1>
    <table class="table table-lg-responsive table-striped">
        <thead>
            <th>ID</th>
            <th>Fecha</th>
            <th>Descripcion</th>
            <th>Realizado</th>
        </thead>
        <tbody>
            {% for manto in object_list  %}
            <tr>
                <td>{{ manto.id }}</td>
                <td>{{ manto.fecha }}</td>
                <td>{{ manto.descripcion }}</td>
                {% if manto.aplicado %}
                <td>
                    <button class="btn btn-secondary">Hecho</button>
                    <a href="{% url 'manto:deleteManto' manto.id %}" class="btn btn-danger">Eliminar</a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'manto:checkList' manto.id %}" class="btn btn-success">Pendiente</a>
                    <a href="{% url 'manto:updateManto' manto.id %}" class="btn btn-primary">Modificar</a>
                    <a href="{% url 'manto:deleteManto' manto.id %}" class="btn btn-danger">Eliminar</a>
                </td>
                {% endif %}
                
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h1 class="text-center">No hay mantenimientos registrados</h1>
    {% endif %}
</div>
{% endblock content %}

templates/manto/mantoNew.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class='container contenedor'>
    <h1 class="text-center">Nuevo Mantenimiento</h1>
		<div class="row justify-content-center">
			<div class="col-sm-6">
				<form method="POST">
					{% csrf_token %}
                    <div class="form-group">
                        <label for="id_fecha">Fecha del servicio</label>
                        <div class='input-group' id='datepicker' data-provide='datepicker'>
                            {{form.fecha}}
                            <div class="input-group-append">
                                <div class='input-group-text'><i class='fa-calendar'></i></div>
                            </div>
                        </div>
                    </div>
                    <div class='form-group'>
                        <label for="descripcion">Descripcion del servicio</label>
                        {{ form.descripcion }}
                    </div>
					<button type="submit" class="btn btn-primary btn-block btn-lg">Agregar</button>
				</form>
			</div>
        </div>
</div>
{% endblock content %}