area/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from area import views
from area.views import (AreaCreateView,
						 AreaDeleteView,
						 AreaListView,
						 AreaUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(AreaCreateView.as_view()), name='newArea'),
	url(r'^lista/areas', login_required(AreaListView.as_view()), name='listAreas'),
	url(r'^modificar/area/(?P<pk>\d+)', login_required(AreaUpdateView.as_view()), name='updateArea'),
	url(r'^eliminar/area/(?P<pk>\d+)', login_required(AreaDeleteView.as_view()), name='deleteArea'),
	url(r'^menu-areas/', login_required(views.menuAreas), name='menu_areas')
]

insumos/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from insumos import views

from insumos.views import InsumosCreateView, InsumosDeleteView, InsumosListView, InsumosUpdateView

urlpatterns = [
	url(r'^nuevo/insumos/', login_required(InsumosCreateView.as_view()), name='newInsumo'),
	url(r'^lista/insumos/$', login_required(InsumosListView.as_view()), name='listInsumo'),
	url(r'^editar/insumos/(?P<pk>\d+)', login_required(InsumosUpdateView.as_view()), name='updateInsumo'),
	url(r'^eliminar/insumos/(?P<pk>\d+)', login_required(InsumosDeleteView.as_view()), name='deleteInsumo'),

    ##### url del ajax ####
    url(r'^insumo/detalle/$', views.DetailAjax, name='home')    

]

manto/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from manto.views import MantenimientoCreateView, MantenimientoListView, MantenimientoUpdateView, MantenimientoDeleteView
from manto import views

urlpatterns = [
    url(r'^nuevo/', login_required(MantenimientoCreateView.as_view()), name='newManto'),
    url(r"^modificar/(?P<pk>\d+)", login_required(MantenimientoUpdateView.as_view()), name="updateManto"),
    url(r"^eliminar/(?P<pk>\d+)", login_required(MantenimientoDeleteView.as_view()), name="deleteManto"),
    
    url(r'^lista/$', login_required(MantenimientoListView.as_view()), name='listManto'),
    url(r"^lista/(?P<pk>\d+)", login_required(views.MantenimientoRealizadoUpdate), name="checkList"),
    url(r'^fecha_manto/$', login_required(views.fechaManto), name="fechaManto"),
    
]

prendas/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from prendas.views import (PrendasCreateView, 
							PrendasDeleteView, 
							PrendasListView, 
							PrendasUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(PrendasCreateView.as_view()), name='newPrenda'),
	url(r'^lista/', login_required(PrendasListView.as_view()), name='listPrenda'),
	url(r'^modificar/(?P<pk>\d+)', login_required(PrendasUpdateView.as_view()), name='updatePrenda'),
	url(r'^eliminar/(?P<pk>\d+)', login_required(PrendasDeleteView.as_view()), name='deletePrenda'),
]

scir/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from usuario import views

urlpatterns = [
	url(r'^$', views.index, name='first'),
	url(r'^menu/$', login_required(views.menuPrincipal), name='menuPrincipal'),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^area/', include('area.urls', namespace='area')),
    url(r'^prendas/', include('prendas.urls', namespace = 'prendas')),
    url(r'^insumos/', include('insumos.urls', namespace = 'insumos')),
    url(r'^solicitud/', include('solicitud.urls', namespace='solicitud')),
    url(r'^mantenimiento/', include('manto.urls', namespace='manto')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

usuario/urls.py
from django.conf.urls import url

from usuario import views
from usuario.views import UserListView

urlpatterns = [
	url(r'^registrar/', views.signUp, name='signup'),
	url(r'^lista/', UserListView.as_view(), name='listUser'),
]

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>INER Lavanderia</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- hojas d estilos creada por el author -->
    <link rel="stylesheet" type="text/css" href="{% static "css/estilo.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/menuAreas.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/servicios.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/reportes.css" %}">
    <link rel='stylesheet' type="text/css" href='//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css'>
  </head>
  <body>
<!-- NAVBAR
================================================== -->
  {% include "navbar.html" %}

  {% block content %}
        
  {% endblock content %}
     
      
  {% block modal-ventana %}
        
  {% endblock modal-ventana %}
  <!-- FOOTER -->
<footer class="bg-dark fixed-bottom">
    <div class="text-center mt-3">
        <p> &copy; 2016 T.E.D, Inc. &middot; 
            <a href="#">Privacy</a> &middot; 
            <a href="#">Terms</a>
        </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
        ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static "js/contador.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "js/insumos.js" %}" type="text/javascript" charset="utf-8" async defer></script>

<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static "js/ajaxSol.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static 'js/manto.js' %}"></script>
<script src='https://code.jquery.com/ui/1.12.1/jquery-ui.js'></script>
<script>
  

  function recorrer(array, propiedad){

    array.map(
      propiedad ? elemento => recorrer(elemento[propiedad])
      : elemento => $('#option').append('<option value="'+elemento[0]+'">'+elemento+'</option>')
    );
  }

   $('#anio').change(function(){
      if($('#anio').val() !== 0){
        $('#options').prop('disabled', false);
        $('#option').prop('disabled', false);
      }else{
        $('#options').prop('disabled', 'disabled');
        $('#options').val() = 0;
        $('#option').prop('disabled', 'disabled');
        $('#option').val() = 0;
      }
    });

   var opciones = []
    opciones.push({
      semestral : ['primer semestre', 'segundo semestre'],
      trimestral : ['Primer trimestre', 'Segundo trimestre','Tercer trimestre','Cuarto trimestre'],
      bimestral : ['Primer bimestre', 'Segundo bimestre','Tercer bimestre','Cuarto bimestre','Quinto bimestre','Sexto bimestre'],
      mensual : ['Enero', 'Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
    });

    var select = document.getElementById('options');
  
  $('#options').change(function(){

    var str = this.options[select.selectedIndex];
    document.getElementById("option").length=0;
    recorrer(opciones, str.text);
    
  });

</script>

<script>
  $(function(){
    $('#id_fecha').datepicker({
      dateFormat: "yy-mm-dd",
    });

  });

</script>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
	<div class="container mt-5">
	    <h1 class="text-center">Bienvenido</h1>
		<div class="row">	
			<div class="col-12 text-center">
				<img  src="{% static "img/image.jpg" %}" alt="" height="350px" width="300px">
			</div>
			<div class="col-12 text-center">
				<a href="{% url 'auth_login' %}" type="button" class="btn btn-primary btn-inicio">Iniciar sesión</a>
			</div>	
		</div>
	</div>
	
{% endblock content %}
	
		

templates/navbar.html
<body>
{% if request.user.is_authenticated %}
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url "menuPrincipal" %}">S.C.I.R.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if request.user.is_superuser %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url "menuPrincipal" %}">Menú<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "usuario:listUser" %}">Usuarios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "prendas:listPrenda" %}">Prendas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "area:listAreas" %}">Áreas</a>
        </li>
        <li class="nav-item">
          <a href="{% url "insumos:listInsumo" %}" class="nav-link">Insumos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'solicitud:newSolicitud' %}">Solicitud de servicio</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url "menuPrincipal" %}">Menú<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'solicitud:newSolicitud' %}">Solicitud de servicio</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mantenimento
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'manto:listManto' %}">Lista de manto</a>
            <a class="dropdown-item" href="{% url 'manto:newManto' %}">Nuevo mantenimiento</a>
          </div>
        </li>
      </ul>
      <ul class="nav navbar-nav justify-content-end" >
          {% if request.user.is_authenticated %}
          <li class="nav-item" >
            <a href="#" class="nav-link active" >{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'auth_logout' %}" class="btn btn-outline-info my-2 my-sm-0 ">Salir</a>
          </li>
          {% endif %}
      </ul>
    </div>
  </nav>
{% endif %}