area/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from area import views
from area.views import (AreaCreateView,
						 AreaDeleteView,
						 AreaListView,
						 AreaUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(AreaCreateView.as_view()), name='newArea'),
	url(r'^lista/areas', login_required(AreaListView.as_view()), name='listAreas'),
	url(r'^modificar/area/(?P<pk>\d+)', login_required(AreaUpdateView.as_view()), name='updateArea'),
	url(r'^eliminar/area/(?P<pk>\d+)', login_required(AreaDeleteView.as_view()), name='deleteArea'),
	url(r'^menu-areas/', login_required(views.menuAreas), name='menu_areas')
]

prendas/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from prendas.views import (PrendasCreateView, 
							PrendasDeleteView, 
							PrendasListView, 
							PrendasUpdateView)

urlpatterns = [
	url(r'^nueva/', login_required(PrendasCreateView.as_view()), name='newPrenda'),
	url(r'^lista/', login_required(PrendasListView.as_view()), name='listPrenda'),
	url(r'^modificar/(?P<pk>\d+)', login_required(PrendasUpdateView.as_view()), name='updatePrenda'),
	url(r'^eliminar/(?P<pk>\d+)', login_required(PrendasDeleteView.as_view()), name='deletePrenda'),
]

scir/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from usuario import views

urlpatterns = [
	url(r'^$', views.index, name='first'),
	url(r'^menu/$', login_required(views.menuPrincipal), name='menuPrincipal'),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^area/', include('area.urls', namespace='area')),
    url(r'^prendas/', include('prendas.urls', namespace = 'prendas')),
    url(r'^insumos/', include('insumos.urls', namespace = 'insumos')),
    url(r'^solicitud/', include('solicitud.urls', namespace='solicitud')),
    url(r'^mantenimiento/', include('manto.urls', namespace='manto')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

prendas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Prendas(models.Model):

    class Meta:
        verbose_name = "Prendas"
        verbose_name_plural = "Prendas"
        
    nombre_prenda = models.CharField(max_length = 255)
    no_prendas = models.IntegerField()
    
    def __str__(self):
        return self.nombre_prenda
    

prendas/forms.py
from django import forms
from prendas.models import Prendas


class PrendasForm(forms.ModelForm):
    class Meta:
        model = Prendas
        fields = '__all__'

        labels = {
        	'nombre_prenda' : 'Prenda',
        	'no_prendas' : 'Stock'
        }
    

prendas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy


from django.views.generic.edit import (
		CreateView,
		UpdateView,
		DeleteView
	)

from django.views.generic import ListView


## importacion de modelos
from prendas.models import Prendas

## importacion de formularios

from prendas.forms import PrendasForm
# Create your views here.

class PrendasCreateView(CreateView):
    model = Prendas
    template_name = "prendas/newPrenda.html"
    form_class = PrendasForm
    success_url = reverse_lazy('prendas:listPrenda')

    def get_context_data(self, **kwargs):
        context = super(PrendasCreateView, self).get_context_data(**kwargs)
        if 'form2' not in context:
        	context['form2'] = self.form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
    	self.object = self.get_object
    	form2 = self.form_class(request.POST)
    	if form2.is_valid():
    		prenda = form2.save()
    		return HttpResponseRedirect(self.get_success_url())
    	else:
    		return self.render_to_response(self.get_context_data(form=form2))

class PrendasListView(ListView):
    model = Prendas
    template_name = "prendas/listPrenda.html"

class PrendasUpdateView(UpdateView):
    model = Prendas
    template_name = "prendas/newPrenda.html"
    form_class = PrendasForm
    success_url = reverse_lazy('prendas:listPrenda')

class PrendasDeleteView(DeleteView):
    model = Prendas
    template_name = "prendas/deletePrenda.html"
    success_url = reverse_lazy('prendas:listPrenda')

templates/prendas/deletePrenda.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block title %}Eliminar {{ object.codigo }}{% endblock %}
{% block content %}
	<div class="row">
		<h1 class="text-align-center">¿Estás seguro que deseas borrar el Usuario "{{ object.codigo }}"?</h1>
		<p class="text-align-center">{{object.nombre_prenda}}</p>
		<div class="col-sm-6 col-sm-offset-3">
			<form method="POST">{% csrf_token %}
		    	<input class="btn btn-danger btn-lg" type="submit" value="Eliminar" />
		    	<br/>
			</form>
			
			<a href="{% url "prendas:listPrenda" %}"><button class="btn btn-primary btn-lg">Cancelar</button></a>
		</div>
	</div>
{% endblock %}

templates/prendas/listPrenda.html
{% extends "base.html" %}

{% block content %}

<div class="container contenedor">
	{% if object_list %}
	<h1 class="text-center">Lista de Prendas</h1>
	<table class="table table-lg-responsive table-striped">
		<thead>
			<th class="center">Prenda</th>
			<th class="center">Stock</th>
			<th class="center">Acciones</th>
		</thead>
		<tbody>
			{% for prendas in object_list %}
			<tr>
				<td align="center">{{prendas.nombre_prenda}}</td>
				<td align="center">{{prendas.no_prendas}}</td>
				<td align="center">
					<a href="{% url 'prendas:updatePrenda' prendas.id %}"><button class="btn btn-primary btn-sm">Editar</button></a>
					<a href="{% url 'prendas:deletePrenda' prendas.id %}"><button class="btn btn-danger btn-sm">Eliminar</button></a>
				</td>
			</tr>
			{% endfor %}

		</tbody>
	</table>
	<a href="{% url 'prendas:newPrenda' %}" class="btn btn-block btn-primary btn-lg">Registrar Ropa</a>
	{% else %}
	<h1 class="text-center">No hay prendas registradas</h1>
	<a href="{% url 'prendas:newPrenda' %}" class="btn btn-block btn-primary btn-lg">Registrar Ropa</a>
	{% endif %}
</div>

{% endblock content %}

templates/prendas/newPrenda.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block content %}
	
<div class="container contenedor">
	<div class="row justify-content-center">
		<div class="col-6" >
			<h1 class="text-center">Nueva Prenda</h1>
			<form method="POST">
				{% csrf_token %}
				{% bootstrap_form form %}
				<button type="submit" class="btn btn-primary btn-lg btn-block">Agregar</button>
			</form>
		</div>
	</div>
	
</div>
	
{% endblock content %}